# Generated by Django 5.2.6 on 2025-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional link to related page (e.g. /contracts/3/)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
    ]
