# Generated by Django 5.2.6 on 2025-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_notification_link_alter_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
