# Generated by Django 5.2.6 on 2025-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('part_time', 'Part-time'), ('busy', 'Busy')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(blank=True),
        ),
    ]
