# Generated by Django 5.2.6 on 2025-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_profile_availability_alter_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_freelancer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('part_time', 'Part-time'), ('busy', 'Busy')], default='available', max_length=20),
        ),
    ]
