# Generated by Django 5.2.6 on 2025-10-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_project_budget_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='marketplace.profile'),
        ),
    ]
