# Generated by Django 5.2.6 on 2025-10-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile_availability_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.CharField(blank=True, choices=[('500', '₹500/hr'), ('1000', '₹1000/hr'), ('1500', '₹1500/hr'), ('2000', '₹2000/hr')], default='500', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
