# Generated by Django 5.2.6 on 2025-10-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_skill_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=models.TextField(default='Standard contract terms apply.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.CharField(choices=[('500', '₹500/hr'), ('1000', '₹1000/hr'), ('1500', '₹1500/hr'), ('2000', '₹2000/hr')], default='500', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.profile'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
