# Generated by Django 5.2.6 on 2025-10-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_contract_status_contract_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
