# Generated by Django 5.2.6 on 2025-10-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_availability_alter_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='freelancer', max_length=20),
        ),
    ]
