# Generated by Django 5.1.2 on 2025-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updateted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
