# Generated by Django 5.1.2 on 2025-10-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_updateted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='updateted_at',
            new_name='updated_at',
        ),
    ]
