# Generated by Django 5.2.7 on 2025-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_proposal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('project', 'freelancer')},
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='core_propos_status_676501_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['created_at'], name='core_propos_created_1f7802_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
