# Generated by Django 5.2.7 on 2025-10-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('message', 'Message'), ('contract', 'Contract'), ('proposal', 'Proposal')], max_length=50),
        ),
    ]
