# Generated by Django 5.2.7 on 2025-10-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_user_type_project_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='time_available',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
