# Generated by Django 5.2.7 on 2025-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_milestone_invoice_payment_projectfile_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, help_text='Project completion deadline', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder has been sent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
