# Generated by Django 5.2.7 on 2025-11-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contract_reminder_sent_contract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.payment'),
        ),
    ]
