# Generated by Django 5.2.6 on 2025-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_options_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(blank=True),
        ),
    ]
