# Generated by Django 5.2.6 on 2025-10-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_proposal_status_alter_contract_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_freelancer', to='core.profile'),
        ),
    ]
