# Generated by Django 5.2.6 on 2025-10-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_proposal_accepted_alter_contract_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
